const express = require("express");
const route = express.Router();
const controller = require("./controller");
const { isAuthenticated, isOwner } = require("./middlewares/index");

route.get("/api/products/Laptopy", controller.prod_NTB);
route.get("/api/products/Komputery", controller.prod_DSK);
route.get("/api/products/Smartphony", controller.prod_PHONE);
route.get("/api/products/Podzespoly-komputerowe", controller.prod_COM);
route.get("/api/products/Akcesoria", controller.prod_ACC);
route.get("/api/products/All", controller.prod_All);
route.get("/api/product/:id", controller.Single_prod);
route.post("/api/add/opinion", controller.AddOpinion);
route.get("/api/get/opinion/:id", controller.GetOpinion);
route.delete("/api/delete/opinion/:id", controller.DeleteOpinion);
route.get("/api/sale/product", controller.SaleProduct);
route.post("/api/order/add", controller.AddOrder);
route.post("/register", controller.Register);
route.post("/login", controller.Login);
route.delete("/users/del/:id", isAuthenticated, isOwner, controller.DeleteUser);
route.put("/users/upd/:id", isAuthenticated, isOwner, controller.UpdateUser);
route.get("/profile", controller.Profile);
route.get("/api/orders/get/:id", controller.GetOrders);
module.exports = route;
